# Use an official Node.js runtime as a parent image
FROM node:20-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of the application's source code
COPY . .

# Expose the Vite default port
EXPOSE 5173

# Run the Vite dev server and ensure it's accessible from outside the container
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
